--- 
blobstore: 
  provider: s3
  options: 
    bucket_name: BOSH
    access_key_id: AKIAIDC76IQWCWDL3QKQ
    secret_access_key: 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
    encryption_key: PERSONAL_RANDOM_KEY
min_cli_version: "0.20"
